In [1]:
import numpy as np
import pandas as pd

In [2]:
new_df = pd.read_csv('tig_suggestion.csv')

In [3]:
new_df.head()

Interest           Item                  ChallengeName  \
0   Sports   Soccer Ball           Soccer Ball Dribbling   
1   Sports     Basketball            Basketball Shooting   
2   Sports  Tennis Racket  Tennis Racket Forehand Stroke   
3   Sports   Baseball Bat           Baseball Bat Hitting   
4   Sports      Golf Club              Golf Club Putting   

                                         Description  
0  Using the feet to control the soccer ball whil...  
1  Throwing the basketball into the hoop from var...  
2  Hitting the tennis ball with the front side of...  
3  Swinging the baseball bat to make contact with...  
4  Using the golf club to gently hit the golf bal...

In [4]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448 entries, 0 to 447
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Interest       448 non-null    object
 1   Item           448 non-null    object
 2   ChallengeName  448 non-null    object
 3   Description    448 non-null    object
dtypes: object(4)
memory usage: 14.1+ KB


In [5]:
new_df['Description']

0      Using the feet to control the soccer ball whil...
1      Throwing the basketball into the hoop from var...
2      Hitting the tennis ball with the front side of...
3      Swinging the baseball bat to make contact with...
4      Using the golf club to gently hit the golf bal...
                             ...                        
443    Create a meal planning template and engage in ...
444    Bike to work or school instead of driving for ...
445    Use plant-based and natural skincare products ...
446    Set up a rainwater harvesting kit to collect r...
447    Use an eco-friendly phone case made from susta...
Name: Description, Length: 448, dtype: object

In [6]:
new_df['Description'][1]

'Throwing the basketball into the hoop from various distances and angles, aiming for accuracy and consistent form.'

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000,stop_words='english')

In [8]:
vector = cv.fit_transform(new_df['Description']).toarray()

In [9]:
vector.shape

(448, 2000)

In [10]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [11]:
(cv.get_feature_names_out())

array(['30', 'absorbing', 'abstract', ..., 'zester', 'zip', 'ziplock'],
      dtype=object)

In [12]:
len(new_df['Description'][0])

131

In [13]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
cv

CountVectorizer(max_features=2000, stop_words='english')

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
similarity = cosine_similarity(vector)

In [17]:
similarity

array([[1.        , 0.        , 0.20100756, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.20100756, 0.        , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.07692308,
        0.16012815],
       [0.        , 0.        , 0.        , ..., 0.07692308, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.16012815, 0.        ,
        1.        ]])

In [18]:
cosine_similarity(vector).shape

(448, 448)

In [19]:
similarity[0]

array([1.        , 0.        , 0.20100756, 0.        , 0.1672484 ,
       0.0836242 , 0.09090909, 0.07312724, 0.        , 0.09090909,
       0.        , 0.15075567, 0.        , 0.        , 0.0836242 ,
       0.        , 0.09090909, 0.        , 0.09090909, 0.0836242 ,
       0.0836242 , 0.0836242 , 0.        , 0.08703883, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08703883, 0.        , 0.        , 0.        , 0.        ,
       0.08703883, 0.        , 0.        , 0.0805823 , 0.08703883,
       0.        , 0.        , 0.0836242 , 0.08703883, 0.0836242 ,
       0.        , 0.        , 0.07784989, 0.        , 0.09090909,
       0.08703883, 0.0805823 , 0.08703883, 0.        , 0.06428243,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.09534626,
       0.        , 0.        , 0.31980107, 0.        , 0.     

In [28]:
def recommend(tig_name):
    nl = '\n'
    index = new_df[new_df['ChallengeName'] == tig_name].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(f"Challenge Name : {new_df.iloc[i[0]].ChallengeName} {nl}Challenge Description : {new_df.iloc[i[0]].Description}")        

In [32]:
recommend('Cricket Bat Batting')


Challenge Name : Tennis Racket Forehand Stroke 
Challenge Description : Hitting the tennis ball with the front side of the racket while maintaining proper technique and generating power and spin.
Challenge Name : Rugby Ball Tackling 
Challenge Description : Bringing down the opponent carrying the rugby ball by grasping and pulling them to the ground during a rugby match.
Challenge Name : Table Tennis Paddle Backhand Loop 
Challenge Description : Using the backhand stroke with the table tennis paddle to generate topspin and loop the ball over the net during a table tennis match.
Challenge Name : Volleyball Spiking 
Challenge Description : Jumping and hitting the volleyball forcefully downward into the opponent's court, often done near the net.
Challenge Name : Badminton Shuttlecock Smash Shot 
Challenge Description : Hitting the badminton shuttlecock with a swift and forceful downward motion to put it past the opponent 


In [33]:
import pickle

In [31]:
pickle.dump(new_df,open('tig_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))